# Generated by Django 6.0.2 on 2026-02-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('core', '0004_alter_profile_options_profile_user_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='The profile/user this message is associated with (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='core.profile'),
        ),
    ]
