# Generated by Django 6.0.2 on 2026-02-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='profile',
        ),
    ]
