# Generated by Django 6.0.2 on 2026-02-18 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_profile_options_profile_user_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolios/')),
                ('link', models.URLField(blank=True, help_text='Optional external link (e.g., publication, presentation)')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g., research, case study, presentation', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in home page featured section?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.profile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Optional price if it's a paid service/program", max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('available', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, help_text='Booking/registration link')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
