# Generated by Django 6.0.2 on 2026-02-14 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Dr. Olana Wakoya Gichile', max_length=100)),
                ('title', models.CharField(default='MD, MSc | Lecturer & General Practitioner', max_length=100)),
                ('bio', models.TextField(default='A dedicated clinician-educator passionate about global health equity, medical education, and improving access to quality healthcare in resource-limited settings.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('years_experience', models.PositiveIntegerField(default=10)),
                ('specialization', models.CharField(default='Global Health, Internal Medicine, Medical Education', max_length=200)),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/olana-wakoya-gichile-a02483168')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
