# Generated by Django 6.0.2 on 2026-02-14 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clinical', 'Clinical Skills'), ('technical', 'Technical Skills'), ('soft', 'Soft Skills'), ('language', 'Languages')], default='clinical', max_length=50)),
                ('proficiency', models.CharField(blank=True, max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.profile')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
